### ISSUE TITLE
Bugs in ROMS data frame

### ISSUE THREAD

**Issue by okenk** [pacific-hake/ss3roms#10]
-999 in ROMS data frame is getting read as actual data

**Comment by kellijohnson-NOAA** [comment]
I coded it that way because I thought that -999 would be predicted bc "index" should also be negative telling SS3 that the value isn't observed like what we have for the age-2+ survey for years that are not sampled
https://github.com/pacific-hake/ss3roms/blob/36c1ca5a83c80e21c68858ebf83d41f8621cf778/R/add_fleet.R#L158-L161

**Comment by okenk** [comment]
Got it. I think this caused issues when I tried to invert the index (since recruitment is negatively associated with the driver) because it was no longer 999.

**Comment by kellijohnson-NOAA** [comment]
Ahh, sorry about that. I never thought about transformation of the data.
