### ISSUE TITLE
Units of age-0 index

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/ss3roms#7]
https://github.com/pacific-hake/ss3roms/blob/47bad77252e4161a6bcd23efc44b728f727570ef/R/add_fleet.R#L114

@okenk here is where we need to be careful that we are using the "correct" units. 0 means numbers. There are other options in Stock Synthesis as far as modeling with 30+ numbers that correspond with special survey types.

**Comment by kellijohnson-NOAA** [comment]
And, if we use 30+ there are probably changes to the code that would be needed to add extra information when needed, not sure.

**Comment by okenk** [comment]
It looks like units = 31 is for exp(recruitment deviation) so is what we should use. In this case we do not need to specify min and max age for the selectivity curve.

**Comment by okenk** [comment]
@kellijohnson-NOAA, I tried specifying `units = 31` :
1. First I ran it as is. I don't think anything changed.
2. I tried adding an if statement at line 185 of add_fleet.R since the SS manual says selectivity should not be specified for units >= 30. It could not read the control file, with error "Invalid index -1002 used for array range [0, 50] in "int& ivector::operator() (int i)".
array bound exceeded -- index too low"

I think that catchability might also need to be specified differently, though could not figure out how to do it from the manual. It's also DEFINITELY possible what I did with selectivity was wrong.

**Comment by kellijohnson-NOAA** [comment]
Can you go to the bottom of echoinput and see what section it got to? I am guessing weight-at-age

**Comment by okenk** [comment]
the file ends during/after selectivity (selex types)

**Comment by okenk** [comment]
Function now handles `units = 0` with ages either fully or not selected and `units = 31`, exp(recruitment deviations). 36c1ca5a83c80e21c68858ebf83d41f8621cf778
